name: tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

  push:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout changes
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        find frameworks | grep requirements.txt | xargs -n 1 pip install -r
        pip install pytest pytest-aio

    - name: Test with pytest
      run: |
        pytest frameworks
